version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bot-for-humanity"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2e4djvei43ss"
s3_prefix = "bot-for-humanity"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
